# Generated by Django 4.1.5 on 2023-02-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
